version: 1.6.{build}
image: Visual Studio 2019
configuration: ReleaseCI
init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - ExpressionTreeToString/
    - Shared/
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore

matrix:
  fast_finish: true

artifacts:
  - path: ExpressionTreeToString\bin\ReleaseCI\*.nupkg
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: ggnvR8rEMLbVOYOAMBXmjD+ohPaPoCcMwwEPdQvMbpjt+HEHWFxZYNGXs+O1x8tD
    artifact: /.*\.nupkg/